let g:indent_blankline_char = '|'
let g:indent_blankline_char_list =  '┊'
let g:indent_blankline_char_highlight_list = ['Error', 'Function']
let g:indent_blankline_space_char = ' '
let g:indent_blankline_space_char_blankline = ' '
let g:indent_blankline_space_char_highlight_list = ['Error', 'Function']
let g:indent_blankline_space_char_blankline_highlight_list = ['Error', 'Function']
let g:indent_blankline_use_treesitter = v:true
let g:indent_blankline_show_end_of_line = v:true
